# 配置文件优先级 https://gitee.com/xinqiyi1024/picgobag/raw/master/img/202203031026399.png
server:
  port: 8081

# 数据库连接
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: wiki
    password: wiki123
    url: jdbc:mysql://localhost:3306/wiki?serviceTimezone=Asia/Shanghai&useSSL=true&characterEncoding=utf8

# 配置mybatis所有Mapper.xml所在路径
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml

logging:
  level:
    com.fzn.wiki.mapper:
      trace